package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserReadLog generated by hbm2java
 */
public class UserReadLog extends BaseEntity {

    private Long id;
    private long userId;
    private long bookId;
    private Date readTime;
    private Integer type;
    private Integer page;
    private Long activityId;
    private Date creationTime;

    public UserReadLog() {
    }

    public UserReadLog(long userId, long bookId) {
        this.userId = userId;
        this.bookId = bookId;
    }

    public UserReadLog(long userId, long bookId, Date readTime, Integer type, Integer page, Long activityId,
            Date creationTime) {
        this.userId = userId;
        this.bookId = bookId;
        this.readTime = readTime;
        this.type = type;
        this.page = page;
        this.activityId = activityId;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getBookId() {
        return this.bookId;
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    public Date getReadTime() {
        return this.readTime;
    }

    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getPage() {
        return this.page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Long getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
