package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserVisitLast generated by hbm2java
 */
public class UserVisitLast extends BaseEntity {

    private Long id;
    private Long userId;
    private Long visitUserId;
    private Date visitDate;

    public UserVisitLast() {
    }

    public UserVisitLast(Long userId, Long visitUserId, Date visitDate) {
        this.userId = userId;
        this.visitUserId = visitUserId;
        this.visitDate = visitDate;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getVisitUserId() {
        return this.visitUserId;
    }

    public void setVisitUserId(Long visitUserId) {
        this.visitUserId = visitUserId;
    }

    public Date getVisitDate() {
        return this.visitDate;
    }

    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
