package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.math.BigDecimal;

import cn.chineseall.model.BaseEntity;

/**
 * UserLevel generated by hbm2java
 */
public class UserLevel extends BaseEntity {

    private Long id;
    private Integer minPoints;
    private Integer maxPoints;
    private String level;
    private String classic;
    private Integer joinOrgNumber;
    private Integer borrowBookNumber;
    private BigDecimal vipDiscount;

    public UserLevel() {
    }

    public UserLevel(Integer minPoints, Integer maxPoints, String level, String classic, Integer joinOrgNumber,
            Integer borrowBookNumber, BigDecimal vipDiscount) {
        this.minPoints = minPoints;
        this.maxPoints = maxPoints;
        this.level = level;
        this.classic = classic;
        this.joinOrgNumber = joinOrgNumber;
        this.borrowBookNumber = borrowBookNumber;
        this.vipDiscount = vipDiscount;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getMinPoints() {
        return this.minPoints;
    }

    public void setMinPoints(Integer minPoints) {
        this.minPoints = minPoints;
    }

    public Integer getMaxPoints() {
        return this.maxPoints;
    }

    public void setMaxPoints(Integer maxPoints) {
        this.maxPoints = maxPoints;
    }

    public String getLevel() {
        return this.level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getClassic() {
        return this.classic;
    }

    public void setClassic(String classic) {
        this.classic = classic;
    }

    public Integer getJoinOrgNumber() {
        return this.joinOrgNumber;
    }

    public void setJoinOrgNumber(Integer joinOrgNumber) {
        this.joinOrgNumber = joinOrgNumber;
    }

    public Integer getBorrowBookNumber() {
        return this.borrowBookNumber;
    }

    public void setBorrowBookNumber(Integer borrowBookNumber) {
        this.borrowBookNumber = borrowBookNumber;
    }

    public BigDecimal getVipDiscount() {
        return this.vipDiscount;
    }

    public void setVipDiscount(BigDecimal vipDiscount) {
        this.vipDiscount = vipDiscount;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
