package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserReadGroupUser generated by hbm2java
 */
public class UserReadGroupUser extends BaseEntity {

	private static final long serialVersionUID = -3690145147380951094L;
	private Long id;
	private long groupId;
	private long userId;
	private Integer state; // 状态（0-申请加入；1-已加入；2-升级管理员）
	private Date creationTime;
	private Integer type;
	private Integer isLively;

	public UserReadGroupUser() {
	}

	public UserReadGroupUser(long groupId, long userId, int state) {
		this.groupId = groupId;
		this.userId = userId;
		this.state = state;
	}

	public Integer getIsLively() {
		return isLively;
	}

	public void setIsLively(Integer isLively) {
		this.isLively = isLively;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public UserReadGroupUser(long groupId, long userId, int state,
			Date creationTime) {
		this.groupId = groupId;
		this.userId = userId;
		this.state = state;
		this.creationTime = creationTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	/**
	 * @see cn.chineseall.model.BaseEntity#getKeyword()
	 */
	@Override
	public String getKeyword() {
		// TODO Auto-generated method stub
		return null;
	}

}
