package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserStar generated by hbm2java
 */
public class UserStar extends BaseEntity {

    private Long id;
    private long userId;
    private Long orgTreeId;
    private Date recommentTime;
    private String userName;
    private Date creationTime;

    public UserStar() {
    }

    public UserStar(long userId) {
        this.userId = userId;
    }

    public UserStar(long userId, Long orgTreeId, Date recommentTime, String userName, Date creationTime) {
        this.userId = userId;
        this.orgTreeId = orgTreeId;
        this.recommentTime = recommentTime;
        this.userName = userName;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public Date getRecommentTime() {
        return this.recommentTime;
    }

    public void setRecommentTime(Date recommentTime) {
        this.recommentTime = recommentTime;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
