package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.List;

import cn.chineseall.model.BaseEntity;
import cn.chineseall.model.book.Book;

/**
 * UserCollection generated by hbm2java
 */
public class UserCollectGroup extends BaseEntity {

    private Long id;
	private long userId;
    private String name;
    private Integer status;
    private List<Book> books;
    private Long bookCount;
    public Long getBookCount() {
		return bookCount;
	}
	public void setBookCount(Long bookCount) {
		this.bookCount = bookCount;
	}
	public Long getId() {
		return id;
	}
	public List<Book> getBooks() {
		return books;
	}
	public void setBooks(List<Book> books) {
		this.books = books;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public long getUserId() {
		return userId;
	}
	public void setUserId(long userId) {
		this.userId = userId;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	@Override
	public String getKeyword() {
		// TODO Auto-generated method stub
		return null;
	}
}
