package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserLetterGroup generated by hbm2java
 */
public class UserLetterGroup extends BaseEntity {

	private Long id;
	private Long userId;
	private Long groupUserId;
	private Date lastUpdateTime;
	private Integer notReadLetterCount;
	private String title;
	private String content;

	public UserLetterGroup() {
	}

	public UserLetterGroup(Long userId, Long groupUserId, Date lastUpdateTime,
			Integer notReadLetterCount, String title, String content) {
		this.userId = userId;
		this.groupUserId = groupUserId;
		this.lastUpdateTime = lastUpdateTime;
		this.notReadLetterCount = notReadLetterCount;
		this.title = title;
		this.content = content;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getGroupUserId() {
		return this.groupUserId;
	}

	public void setGroupUserId(Long groupUserId) {
		this.groupUserId = groupUserId;
	}

	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getNotReadLetterCount() {
		return this.notReadLetterCount;
	}

	public void setNotReadLetterCount(Integer notReadLetterCount) {
		this.notReadLetterCount = notReadLetterCount;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * @see cn.chineseall.model.BaseEntity#getKeyword()
	 */
	@Override
	public String getKeyword() {
		// TODO Auto-generated method stub
		return null;
	}

}
