package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserVip generated by hbm2java
 */
public class UserVip extends BaseEntity {

    private long userId;
    private Date vipStartDate;
    private Date vipExpiredDate;

    public UserVip() {
    }

    public UserVip(long userId) {
        this.userId = userId;
    }

    public UserVip(long userId, Date vipStartDate, Date vipExpiredDate) {
        this.userId = userId;
        this.vipStartDate = vipStartDate;
        this.vipExpiredDate = vipExpiredDate;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public Date getVipStartDate() {
        return this.vipStartDate;
    }

    public void setVipStartDate(Date vipStartDate) {
        this.vipStartDate = vipStartDate;
    }

    public Date getVipExpiredDate() {
        return this.vipExpiredDate;
    }

    public void setVipExpiredDate(Date vipExpiredDate) {
        this.vipExpiredDate = vipExpiredDate;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
