package cn.chineseall.model.user;

import cn.chineseall.model.BaseEntity;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * UserConfig generated by hbm2java
 */
public class UserConfig extends BaseEntity {

    private Long id;
    private long orgTreeId;
    private Integer isOpen;
    private Integer state;

    public UserConfig() {
    }

    public UserConfig(long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public UserConfig(long orgTreeId, Integer isOpen, Integer state) {
        this.orgTreeId = orgTreeId;
        this.isOpen = isOpen;
        this.state = state;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public Integer getIsOpen() {
        return this.isOpen;
    }

    public void setIsOpen(Integer isOpen) {
        this.isOpen = isOpen;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
