package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserLogin generated by hbm2java
 */
public class UserLogin extends BaseEntity {

    private long userId;
    private String userName;
    private String userPass;
    private String displayName;
    private String realName;
    private Long orgTreeId;
    private String lastLoginIp;
    private Date lastloginTime;
    private String lastLoginSessionId;

    public UserLogin() {
    }

    public UserLogin(long userId) {
        this.userId = userId;
    }

    public UserLogin(long userId, String userName, String userPass, String displayName, String realName,
            Long orgTreeId, String lastLoginIp, Date lastloginTime, String lastLoginSessionId) {
        this.userId = userId;
        this.userName = userName;
        this.userPass = userPass;
        this.displayName = displayName;
        this.realName = realName;
        this.orgTreeId = orgTreeId;
        this.lastLoginIp = lastLoginIp;
        this.lastloginTime = lastloginTime;
        this.lastLoginSessionId = lastLoginSessionId;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPass() {
        return this.userPass;
    }

    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getRealName() {
        return this.realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public String getLastLoginIp() {
        return this.lastLoginIp;
    }

    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    public Date getLastloginTime() {
        return this.lastloginTime;
    }

    public void setLastloginTime(Date lastloginTime) {
        this.lastloginTime = lastloginTime;
    }

    public String getLastLoginSessionId() {
        return this.lastLoginSessionId;
    }

    public void setLastLoginSessionId(String lastLoginSessionId) {
        this.lastLoginSessionId = lastLoginSessionId;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
