package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserReadGroupRecommend generated by hbm2java
 */
public class UserReadGroupRecommend extends BaseEntity {

    private Long id;
    private Long groupId;
    private Long bookId;
    private Long userId;
    private String recommendation;
    private Integer startPage;
    private Integer endPage;
    private Date creationTime;

    public UserReadGroupRecommend() {
    }

    public UserReadGroupRecommend(long groupId, long bookId, long userId) {
        this.groupId = groupId;
        this.bookId = bookId;
        this.userId = userId;
    }

    public UserReadGroupRecommend(long groupId, long bookId, long userId, String recommendation, Integer startPage,
            Integer endPage, Date creationTime) {
        this.groupId = groupId;
        this.bookId = bookId;
        this.userId = userId;
        this.recommendation = recommendation;
        this.startPage = startPage;
        this.endPage = endPage;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getGroupId() {
		return groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	public Long getBookId() {
		return bookId;
	}

	public void setBookId(Long bookId) {
		this.bookId = bookId;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getRecommendation() {
        return this.recommendation;
    }

    public void setRecommendation(String recommendation) {
        this.recommendation = recommendation;
    }

    public Integer getStartPage() {
        return this.startPage;
    }

    public void setStartPage(Integer startPage) {
        this.startPage = startPage;
    }

    public Integer getEndPage() {
        return this.endPage;
    }

    public void setEndPage(Integer endPage) {
        this.endPage = endPage;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
