package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserCollection generated by hbm2java
 */
public class UserCollection extends BaseEntity {

    private Long id;
    private long userId;
    private Long bookId;
    private Date creationTime;
    private Long userCollectGroupId;
    public Long getUserCollectGroupId() {
		return userCollectGroupId;
	}

	public void setUserCollectGroupId(Long userCollectGroupId) {
		this.userCollectGroupId = userCollectGroupId;
	}

	public UserCollection() {
    }

    public UserCollection(long userId) {
        this.userId = userId;
    }

    public UserCollection(long userId, Long bookId, Date creationTime) {
        this.userId = userId;
        this.bookId = bookId;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public Long getBookId() {
        return this.bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
