package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserPayVipLog generated by hbm2java
 */
public class UserPayVipLog extends BaseEntity {

    private Long id;
    private int vipMonthNum;
    private long userId;
    private int chargeType;
    private BigDecimal chargeAmount;
    private String businessCode;
    private String transCode;
    private int resultCode;
    private String validateCode;
    private Date creationTime;

    public UserPayVipLog() {
    }

    public UserPayVipLog(int vipMonthNum, long userId, int chargeType, BigDecimal chargeAmount, String businessCode,
            String transCode, int resultCode, String validateCode) {
        this.vipMonthNum = vipMonthNum;
        this.userId = userId;
        this.chargeType = chargeType;
        this.chargeAmount = chargeAmount;
        this.businessCode = businessCode;
        this.transCode = transCode;
        this.resultCode = resultCode;
        this.validateCode = validateCode;
    }

    public UserPayVipLog(int vipMonthNum, long userId, int chargeType, BigDecimal chargeAmount, String businessCode,
            String transCode, int resultCode, String validateCode, Date creationTime) {
        this.vipMonthNum = vipMonthNum;
        this.userId = userId;
        this.chargeType = chargeType;
        this.chargeAmount = chargeAmount;
        this.businessCode = businessCode;
        this.transCode = transCode;
        this.resultCode = resultCode;
        this.validateCode = validateCode;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getVipMonthNum() {
        return this.vipMonthNum;
    }

    public void setVipMonthNum(int vipMonthNum) {
        this.vipMonthNum = vipMonthNum;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getChargeType() {
        return this.chargeType;
    }

    public void setChargeType(int chargeType) {
        this.chargeType = chargeType;
    }

    public BigDecimal getChargeAmount() {
        return this.chargeAmount;
    }

    public void setChargeAmount(BigDecimal chargeAmount) {
        this.chargeAmount = chargeAmount;
    }

    public String getBusinessCode() {
        return this.businessCode;
    }

    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    public String getTransCode() {
        return this.transCode;
    }

    public void setTransCode(String transCode) {
        this.transCode = transCode;
    }

    public int getResultCode() {
        return this.resultCode;
    }

    public void setResultCode(int resultCode) {
        this.resultCode = resultCode;
    }

    public String getValidateCode() {
        return this.validateCode;
    }

    public void setValidateCode(String validateCode) {
        this.validateCode = validateCode;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
