package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserSmartKey generated by hbm2java
 */
public class UserSmartKey extends BaseEntity {

    private String keyNo;
    private String keyPass;
    private Integer batchNo;
    private Date creationTime;
    private Integer active;
    private Long userId;
    private Date activeTime;

    public UserSmartKey() {
    }

    public UserSmartKey(String keyNo, String keyPass) {
        this.keyNo = keyNo;
        this.keyPass = keyPass;
    }

    public UserSmartKey(String keyNo, String keyPass, Integer batchNo, Date creationTime, Integer active, Long userId,
            Date activeTime) {
        this.keyNo = keyNo;
        this.keyPass = keyPass;
        this.batchNo = batchNo;
        this.creationTime = creationTime;
        this.active = active;
        this.userId = userId;
        this.activeTime = activeTime;
    }

    public String getKeyNo() {
        return this.keyNo;
    }

    public void setKeyNo(String keyNo) {
        this.keyNo = keyNo;
    }

    public String getKeyPass() {
        return this.keyPass;
    }

    public void setKeyPass(String keyPass) {
        this.keyPass = keyPass;
    }

    public Integer getBatchNo() {
        return this.batchNo;
    }

    public void setBatchNo(Integer batchNo) {
        this.batchNo = batchNo;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    public Integer getActive() {
        return this.active;
    }

    public void setActive(Integer active) {
        this.active = active;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Date getActiveTime() {
        return this.activeTime;
    }

    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
