package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserReadGroupReview generated by hbm2java
 */
public class UserReadGroupReview extends BaseEntity {

    private Long id;
    private Long groupId;
    private Long bookId;
    private Long userId;
    private Long recommendId;
    private String review;
    private Date cteationTime;

    public UserReadGroupReview() {
    }

    public UserReadGroupReview(Long groupId, Long bookId, Long userId, Long recommendId) {
        this.groupId = groupId;
        this.bookId = bookId;
        this.userId = userId;
        this.recommendId = recommendId;
    }

    public UserReadGroupReview(Long groupId, Long bookId, Long userId, Long recommendId, String review,
            Date cteationTime) {
        this.groupId = groupId;
        this.bookId = bookId;
        this.userId = userId;
        this.recommendId = recommendId;
        this.review = review;
        this.cteationTime = cteationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public Long getBookId() {
        return this.bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getRecommendId() {
        return this.recommendId;
    }

    public void setRecommendId(Long recommendId) {
        this.recommendId = recommendId;
    }

    public String getReview() {
        return this.review;
    }

    public void setReview(String review) {
        this.review = review;
    }

    public Date getCteationTime() {
        return this.cteationTime;
    }

    public void setCteationTime(Date cteationTime) {
        this.cteationTime = cteationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
