package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserDrafts generated by hbm2java
 */
public class UserDrafts extends BaseEntity {

    private Long id;
    private String title;
    private String content;
    private long userId;
    private String receiveUserId;
    private Long receiveOrgTreeId;
    private Integer state;
    private Date creationTime;

    public UserDrafts() {
    }

    public UserDrafts(String title, long userId) {
        this.title = title;
        this.userId = userId;
    }

    public UserDrafts(String title, String content, long userId, String receiveUserId, Long receiveOrgTreeId,
            Integer state, Date creationTime) {
        this.title = title;
        this.content = content;
        this.userId = userId;
        this.receiveUserId = receiveUserId;
        this.receiveOrgTreeId = receiveOrgTreeId;
        this.state = state;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getReceiveUserId() {
        return this.receiveUserId;
    }

    public void setReceiveUserId(String receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    public Long getReceiveOrgTreeId() {
        return this.receiveOrgTreeId;
    }

    public void setReceiveOrgTreeId(Long receiveOrgTreeId) {
        this.receiveOrgTreeId = receiveOrgTreeId;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
