package cn.chineseall.model.user;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * UserLetter generated by hbm2java
 */
public class UserLetter extends BaseEntity {

    private Long id;
    private Integer type;
    private String title;
    private String content;
    private Long sendUserId;
    private Long receiveUserId;
    private Integer state;	//状态（1:已被发送方删除 2:已被接收方删除 3:全部删除）
    private Long letterId;
    private Date sendTime;
    private Date readTime;
    private Date replyTime;
    private Integer sendType;
    private Long orgTreeId;

    public UserLetter() {
    }

    public UserLetter(Integer type, String title, String content, Long sendUserId, Long receiveUserId, Integer state,
            Long letterId, Date sendTime, Date readTime, Date replyTime, Integer sendType, Long orgTreeId) {
        this.type = type;
        this.title = title;
        this.content = content;
        this.sendUserId = sendUserId;
        this.receiveUserId = receiveUserId;
        this.state = state;
        this.letterId = letterId;
        this.sendTime = sendTime;
        this.readTime = readTime;
        this.replyTime = replyTime;
        this.sendType = sendType;
        this.orgTreeId = orgTreeId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getSendUserId() {
        return this.sendUserId;
    }

    public void setSendUserId(Long sendUserId) {
        this.sendUserId = sendUserId;
    }

    public Long getReceiveUserId() {
        return this.receiveUserId;
    }

    public void setReceiveUserId(Long receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Long getLetterId() {
        return this.letterId;
    }

    public void setLetterId(Long letterId) {
        this.letterId = letterId;
    }

    public Date getSendTime() {
        return this.sendTime;
    }

    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    public Date getReadTime() {
        return this.readTime;
    }

    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    public Date getReplyTime() {
        return this.replyTime;
    }

    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    public Integer getSendType() {
        return this.sendType;
    }

    public void setSendType(Integer sendType) {
        this.sendType = sendType;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
