package cn.chineseall.model.org;

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * OrgAppendModel generated by hbm2java
 */
public class OrgAppendModel extends BaseEntity {

    private static final long serialVersionUID = 1L;
    
    private Long id;
    private Long orgTreeId;
    private String name;
    private String link;
    private Integer isSystem;
    private Integer ranking;
    private Date creationTime;

    public OrgAppendModel() {
    }

    public OrgAppendModel(Long orgTreeId, String name, String link, Integer isSystem, Integer ranking, Date creationTime) {
        this.orgTreeId = orgTreeId;
        this.name = name;
        this.link = link;
        this.isSystem = isSystem;
        this.ranking = ranking;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public Integer getIsSystem() {
        return this.isSystem;
    }

    public void setIsSystem(Integer isSystem) {
        this.isSystem = isSystem;
    }

    public Integer getRanking() {
        return this.ranking;
    }

    public void setRanking(Integer ranking) {
        this.ranking = ranking;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        return this.getClass().getName()+"." + this.getId();
    }

}
