package cn.chineseall.model.org;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * OrgAdverti generated by hbm2java
 */
public class OrgAdverti extends BaseEntity {

    private Long id;
    private String title;
    private String link;
    private String imgUrl;
    private Long orgTreeId;
    private int position;
    private Long pushId;
    private Integer state;
    private Date creationTime;

    public OrgAdverti() {
    }

    public OrgAdverti(int position) {
        this.position = position;
    }

    public OrgAdverti(String title, String link, String imgUrl, Long orgTreeId, int position, Long pushId,
            Integer state, Date creationTime) {
        this.title = title;
        this.link = link;
        this.imgUrl = imgUrl;
        this.orgTreeId = orgTreeId;
        this.position = position;
        this.pushId = pushId;
        this.state = state;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getImgUrl() {
        return this.imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public int getPosition() {
        return this.position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    public Long getPushId() {
        return this.pushId;
    }

    public void setPushId(Long pushId) {
        this.pushId = pushId;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
