package cn.chineseall.model.org;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * OrgBookStatistics generated by hbm2java select b.* from book b left join org_book_statistics_1447 obs on b.id =
 * obs.bookId where obs.orgCode = '1447' and state = 1 order by weekReadCounts desc limit 0,6 select b.* from book b
 * left join org_book_statistics_1447 obs on b.id = obs.bookId where obs.orgCode = '1447' and state = 1 order by
 * collections desc limit 0,6
 */

public class OrgBookStatistics extends BaseEntity {

    private Long id;
    private Long orgTreeId; // 机构编码
    private long bookId; // 图书ID
    private Integer totalReadCounts = 0; // 机构内部总阅读量
    private Integer todayReadCounts = 0; // 机构内部当天阅读量
    private Integer weekReadCounts = 0; // 机构内部本周阅读量
    private Integer monthReadCounts = 0; // 机构内部本月阅读量
    private Integer comments = 0; // 机构内部总评论量
    private Integer collections = 0; // 机构内部总收藏量
    private Integer totalRecommendCounts = 0; // 机构内部总推荐数
    private Integer monthRecommendCounts = 0; // 机构内部当月推荐数
    private Integer scoreUserCount = 0; // 机构内部总评分人数
    private Integer readOrgUserCount = 0; // 本机构内阅读人数
    private Date creationTime; // 创建时间
    
    private String tablePostFix;

    public OrgBookStatistics() {
    }

    public OrgBookStatistics(long bookId) {
        this.bookId = bookId;
    }

    public OrgBookStatistics(Long orgTreeId, long bookId, Integer totalReadCounts, Integer todayReadCounts,
            Integer weekReadCounts, Integer monthReadCounts, Integer comments, Integer collections,
            Integer totalRecommendCounts, Integer monthRecommendCounts, Integer scoreUserCount,
            Integer readOrgUserCount, Date creationTime) {
        this.orgTreeId = orgTreeId;
        this.bookId = bookId;
        this.totalReadCounts = totalReadCounts;
        this.todayReadCounts = todayReadCounts;
        this.weekReadCounts = weekReadCounts;
        this.monthReadCounts = monthReadCounts;
        this.comments = comments;
        this.collections = collections;
        this.totalRecommendCounts = totalRecommendCounts;
        this.monthRecommendCounts = monthRecommendCounts;
        this.scoreUserCount = scoreUserCount;
        this.readOrgUserCount = readOrgUserCount;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public long getBookId() {
        return this.bookId;
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    public Integer getTotalReadCounts() {
        return this.totalReadCounts;
    }

    public void setTotalReadCounts(Integer totalReadCounts) {
        this.totalReadCounts = totalReadCounts;
    }

    public Integer getTodayReadCounts() {
        return this.todayReadCounts;
    }

    public void setTodayReadCounts(Integer todayReadCounts) {
        this.todayReadCounts = todayReadCounts;
    }

    public Integer getWeekReadCounts() {
        return this.weekReadCounts;
    }

    public void setWeekReadCounts(Integer weekReadCounts) {
        this.weekReadCounts = weekReadCounts;
    }

    public Integer getMonthReadCounts() {
        return this.monthReadCounts;
    }

    public void setMonthReadCounts(Integer monthReadCounts) {
        this.monthReadCounts = monthReadCounts;
    }

    public Integer getComments() {
        return this.comments;
    }

    public void setComments(Integer comments) {
        this.comments = comments;
    }

    public Integer getCollections() {
        return this.collections;
    }

    public void setCollections(Integer collections) {
        this.collections = collections;
    }

    public Integer getTotalRecommendCounts() {
        return this.totalRecommendCounts;
    }

    public void setTotalRecommendCounts(Integer totalRecommendCounts) {
        this.totalRecommendCounts = totalRecommendCounts;
    }

    public Integer getMonthRecommendCounts() {
        return this.monthRecommendCounts;
    }

    public void setMonthRecommendCounts(Integer monthRecommendCounts) {
        this.monthRecommendCounts = monthRecommendCounts;
    }

    public Integer getScoreUserCount() {
        return this.scoreUserCount;
    }

    public void setScoreUserCount(Integer scoreUserCount) {
        this.scoreUserCount = scoreUserCount;
    }

    public Integer getReadOrgUserCount() {
        return this.readOrgUserCount;
    }

    public void setReadOrgUserCount(Integer readOrgUserCount) {
        this.readOrgUserCount = readOrgUserCount;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        return null;
    }

    public String getTablePostFix() {
        return tablePostFix;
    }

    public void setTablePostFix(String tablePostFix) {
        this.tablePostFix = tablePostFix;
    }
}
