package cn.chineseall.model.org;

import cn.chineseall.model.BaseEntity;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * OrgBookOrgid generated by hbm2java
 */
public class OrgBookOrgid extends BaseEntity {

    private Long orgTreeId;

    public OrgBookOrgid() {
    }

    public OrgBookOrgid(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
