package cn.chineseall.model.org;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * OrgBaseinfo generated by hbm2java
 */
public class OrgBaseinfo extends BaseEntity {

    private long orgTreeId;
    private String address;
    private String postcode;
    private String phone;
    private String fax;
    private String linkman;
    private Integer gender;
    private String linkmanTel;
    private String linkmanMobile;
    private String linkmanEmail;
    private String description;
    private Date creationTime;
    private String website;
    private String logo;
    private Integer state;
    private String banner;
    private String footerContent;
    private Integer userAudit;
    private int level;
    private Integer regionId;
    private String cssPath;
    private String orgUrl;

    public OrgBaseinfo() {
    }

    public OrgBaseinfo(long orgTreeId, int level) {
        this.orgTreeId = orgTreeId;
        this.level = level;
    }

    public OrgBaseinfo(long orgTreeId, String address, String postcode, String phone, String fax, String linkman,
            Integer gender, String linkmanTel, String linkmanMobile, String linkmanEmail, String description,
            Date creationTime, String website, String logo, Integer state, String banner, String footerContent,
            Integer userAudit, int level, String cssPath, String orgUrl) {
        this.orgTreeId = orgTreeId;
        this.address = address;
        this.postcode = postcode;
        this.phone = phone;
        this.fax = fax;
        this.linkman = linkman;
        this.gender = gender;
        this.linkmanTel = linkmanTel;
        this.linkmanMobile = linkmanMobile;
        this.linkmanEmail = linkmanEmail;
        this.description = description;
        this.creationTime = creationTime;
        this.website = website;
        this.logo = logo;
        this.state = state;
        this.banner = banner;
        this.footerContent = footerContent;
        this.userAudit = userAudit;
        this.level = level;
        this.cssPath = cssPath;
        this.orgUrl = orgUrl;
    }

    public long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getLinkman() {
        return this.linkman;
    }

    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getLinkmanTel() {
        return this.linkmanTel;
    }

    public void setLinkmanTel(String linkmanTel) {
        this.linkmanTel = linkmanTel;
    }

    public String getLinkmanMobile() {
        return this.linkmanMobile;
    }

    public void setLinkmanMobile(String linkmanMobile) {
        this.linkmanMobile = linkmanMobile;
    }

    public String getLinkmanEmail() {
        return this.linkmanEmail;
    }

    public void setLinkmanEmail(String linkmanEmail) {
        this.linkmanEmail = linkmanEmail;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getBanner() {
        return this.banner;
    }

    public void setBanner(String banner) {
        this.banner = banner;
    }

    public String getFooterContent() {
        return this.footerContent;
    }

    public void setFooterContent(String footerContent) {
        this.footerContent = footerContent;
    }

    public Integer getUserAudit() {
        return this.userAudit;
    }

    public void setUserAudit(Integer userAudit) {
        this.userAudit = userAudit;
    }

    public int getLevel() {
        return this.level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public String getCssPath() {
        return this.cssPath;
    }

    public void setCssPath(String cssPath) {
        this.cssPath = cssPath;
    }

    public String getOrgUrl() {
        return this.orgUrl;
    }

    public void setOrgUrl(String orgUrl) {
        this.orgUrl = orgUrl;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        return this.getClass().getName()+"."+this.getOrgTreeId();
    }

    public Integer getRegionId() {
        return regionId;
    }

    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

}
