package cn.chineseall.model.org;

import cn.chineseall.model.BaseEntity;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * OrgIprange generated by hbm2java
 */
public class OrgIprange extends BaseEntity {

    private Long id;
    private Long orgTreeId;
    private String startIp;
    private String endIp;

    public OrgIprange() {
    }

    public OrgIprange(Long orgTreeId, String startIp, String endIp) {
        this.orgTreeId = orgTreeId;
        this.startIp = startIp;
        this.endIp = endIp;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public String getStartIp() {
        return this.startIp;
    }

    public void setStartIp(String startIp) {
        this.startIp = startIp;
    }

    public String getEndIp() {
        return this.endIp;
    }

    public void setEndIp(String endIp) {
        this.endIp = endIp;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
