package cn.chineseall.model.org;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * OrgManyNews generated by hbm2java
 */
public class OrgManyNews extends BaseEntity {

    private Long id;
    private Long orgTreeId;
    private long newsId;
    private Integer isNew;
    private Date newTimeRagne;
    private Integer isTop;
    private Integer topNumber;
    private Integer state;
    private Integer newsSource;

    public OrgManyNews() {
    }

    public OrgManyNews(long newsId) {
        this.newsId = newsId;
    }

    public OrgManyNews(Long orgTreeId, long newsId, Integer isNew, Date newTimeRagne, Integer isTop, Integer topNumber,
            Integer state, Integer newsSource) {
        this.orgTreeId = orgTreeId;
        this.newsId = newsId;
        this.isNew = isNew;
        this.newTimeRagne = newTimeRagne;
        this.isTop = isTop;
        this.topNumber = topNumber;
        this.state = state;
        this.newsSource = newsSource;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public long getNewsId() {
        return this.newsId;
    }

    public void setNewsId(long newsId) {
        this.newsId = newsId;
    }

    public Integer getIsNew() {
        return this.isNew;
    }

    public void setIsNew(Integer isNew) {
        this.isNew = isNew;
    }

    public Date getNewTimeRagne() {
        return this.newTimeRagne;
    }

    public void setNewTimeRagne(Date newTimeRagne) {
        this.newTimeRagne = newTimeRagne;
    }

    public Integer getIsTop() {
        return this.isTop;
    }

    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    public Integer getTopNumber() {
        return this.topNumber;
    }

    public void setTopNumber(Integer topNumber) {
        this.topNumber = topNumber;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getNewsSource() {
        return this.newsSource;
    }

    public void setNewsSource(Integer newsSource) {
        this.newsSource = newsSource;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
