package cn.chineseall.model.org;

import cn.chineseall.model.BaseEntity;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * OrgPageSettings generated by hbm2java
 */
public class OrgPageSettings extends BaseEntity {

    private Long id;
    private String levelCode;
    private Long orgTreeId;
    private String name;
    private Integer isDisplay;

    public OrgPageSettings() {
    }

    public OrgPageSettings(String levelCode, Long orgTreeId, String name, Integer isDisplay) {
        this.levelCode = levelCode;
        this.orgTreeId = orgTreeId;
        this.name = name;
        this.isDisplay = isDisplay;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLevelCode() {
        return this.levelCode;
    }

    public void setLevelCode(String levelCode) {
        this.levelCode = levelCode;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getIsDisplay() {
        return this.isDisplay;
    }

    public void setIsDisplay(Integer isDisplay) {
        this.isDisplay = isDisplay;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
