package cn.chineseall.model.org;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * OrgStatistics generated by hbm2java
 */

public class OrgStatistics extends BaseEntity {

    private long orgTreeId; // 机构树ID
    private String orgName; // 机构名称
    private Integer accessCount; // 本机构人次访问量（页面刷新）
    private Integer accessCountSub; // 下级机构人次访问量（从本表统计）
    private Integer userCount; // 本机构书房数量 user
    private Integer userCountSub; // 下级机构书房数量 user
    private Integer bookCount; // 本机构图书数量 org_book
    private Integer bookCountSub; // 下级机构图书数量 org_book
    private Integer activityCount; // 本机构活动数 ac_baseinfo
    private Integer activityCountSub; // 下级机构活动数 ac_baseinfo
    private Integer points; // 积分（本级） user
    private Integer pointsSub; // 积分（下级机构） user
    private Integer points2011; // 荣誉积分，用于保存1.0旧积分
    private Integer orgCount; // 下级机构数量 org
    private String recommendUser; // 推荐用户，可以为多个用户ID，用逗号分隔 随机推荐
    private Date modifyTime; // 更新时间
    
    public OrgStatistics() {
    }

    public OrgStatistics(long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public OrgStatistics(long orgTreeId, String orgName, Integer accessCount, Integer accessCountSub,
            Integer userCount, Integer userCountSub, Integer bookCount, Integer bookCountSub, Integer activityCount,
            Integer activityCountSub, Integer points, Integer pointsSub, Integer points2011, Integer orgCount,
            String recommendUser, Date modifyTime) {
        this.orgTreeId = orgTreeId;
        this.orgName = orgName;
        this.accessCount = accessCount;
        this.accessCountSub = accessCountSub;
        this.userCount = userCount;
        this.userCountSub = userCountSub;
        this.bookCount = bookCount;
        this.bookCountSub = bookCountSub;
        this.activityCount = activityCount;
        this.activityCountSub = activityCountSub;
        this.points = points;
        this.pointsSub = pointsSub;
        this.points2011 = points2011;
        this.orgCount = orgCount;
        this.recommendUser = recommendUser;
        this.modifyTime = modifyTime;
    }

    public long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public Integer getAccessCount() {
        return this.accessCount;
    }

    public void setAccessCount(Integer accessCount) {
        this.accessCount = accessCount;
    }

    public Integer getAccessCountSub() {
        return this.accessCountSub;
    }

    public void setAccessCountSub(Integer accessCountSub) {
        this.accessCountSub = accessCountSub;
    }

    public Integer getUserCount() {
        return this.userCount;
    }

    public void setUserCount(Integer userCount) {
        this.userCount = userCount;
    }

    public Integer getUserCountSub() {
        return this.userCountSub;
    }

    public void setUserCountSub(Integer userCountSub) {
        this.userCountSub = userCountSub;
    }

    public Integer getBookCount() {
        return this.bookCount;
    }

    public void setBookCount(Integer bookCount) {
        this.bookCount = bookCount;
    }

    public Integer getBookCountSub() {
        return this.bookCountSub;
    }

    public void setBookCountSub(Integer bookCountSub) {
        this.bookCountSub = bookCountSub;
    }

    public Integer getActivityCount() {
        return this.activityCount;
    }

    public void setActivityCount(Integer activityCount) {
        this.activityCount = activityCount;
    }

    public Integer getActivityCountSub() {
        return this.activityCountSub;
    }

    public void setActivityCountSub(Integer activityCountSub) {
        this.activityCountSub = activityCountSub;
    }

    public Integer getPoints() {
        return this.points;
    }

    public void setPoints(Integer points) {
        this.points = points;
    }

    public Integer getPointsSub() {
        return this.pointsSub;
    }

    public void setPointsSub(Integer pointsSub) {
        this.pointsSub = pointsSub;
    }

    public Integer getPoints2011() {
        return this.points2011;
    }

    public void setPoints2011(Integer points2011) {
        this.points2011 = points2011;
    }

    public Integer getOrgCount() {
        return this.orgCount;
    }

    public void setOrgCount(Integer orgCount) {
        this.orgCount = orgCount;
    }

    public String getRecommendUser() {
        return this.recommendUser;
    }

    public void setRecommendUser(String recommendUser) {
        this.recommendUser = recommendUser;
    }

    public Date getModifyTime() {
        return this.modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        return this.getClass().getName()+"."+this.getOrgTreeId();
    }
}
