package cn.chineseall.model.book;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * BookCommentUsefulLog generated by hbm2java
 */
public class BookCommentUsefulLog extends BaseEntity {

    private Long id;
    private long bookCommentId;
    private long userId;
    private Integer ifUseful;  //赞 或 否， 1：赞，0：否
    private Integer state;
    private Date creationTime;

    public BookCommentUsefulLog() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getBookCommentId() {
        return this.bookCommentId;
    }

    public void setBookCommentId(long bookCommentId) {
        this.bookCommentId = bookCommentId;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public Integer getIfUseful() {
        return this.ifUseful;
    }

    public void setIfUseful(Integer ifUseful) {
        this.ifUseful = ifUseful;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
