package cn.chineseall.model.book;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * BookSelfSortBook generated by hbm2java
 */
public class BookSchoolSortBook extends BaseEntity {

    private static final long serialVersionUID = 4272315327007787608L;
    
    private Integer id;
    private Long bookId;
    private Integer schoolSortId;
    private Date creationTime;

    public BookSchoolSortBook() {
    }


    public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public Long getBookId() {
		return bookId;
	}


	public void setBookId(Long bookId) {
		this.bookId = bookId;
	}


	public Date getCreationTime() {
		return creationTime;
	}


	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}


	public void setSchoolSortId(Integer schoolSortId) {
		this.schoolSortId = schoolSortId;
	}


	/**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }


	public Integer getSchoolSortId() {
		return schoolSortId;
	}



}
