package cn.chineseall.model.book;

import cn.chineseall.model.BaseEntity;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * BooksLevel generated by hbm2java
 */
public class BooksLevel extends BaseEntity {

    private Long id;
    private Integer levelId;
    private String levelName;
    private Long bookId;

    public BooksLevel() {
    }

    public BooksLevel(Integer levelId, String levelName, Long bookId) {
        this.levelId = levelId;
        this.levelName = levelName;
        this.bookId = bookId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getLevelId() {
        return this.levelId;
    }

    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    public String getLevelName() {
        return this.levelName;
    }

    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    public Long getBookId() {
        return this.bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
