package cn.chineseall.model.book;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * BookSelfSortBook generated by hbm2java
 */
public class BookSelfSortBook extends BaseEntity {

    private Long id;
    private long bookId;
    private long selfSortId;
    private Date creationTime;

    public BookSelfSortBook() {
    }

    public BookSelfSortBook(long bookId, long selfSortId) {
        this.bookId = bookId;
        this.selfSortId = selfSortId;
    }

    public BookSelfSortBook(long bookId, long selfSortId, Date creationTime) {
        this.bookId = bookId;
        this.selfSortId = selfSortId;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getBookId() {
        return this.bookId;
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    public long getSelfSortId() {
        return this.selfSortId;
    }

    public void setSelfSortId(long selfSortId) {
        this.selfSortId = selfSortId;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
