package cn.chineseall.model.book;

import cn.chineseall.model.BaseEntity;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * BookInfo generated by hbm2java
 */
public class BookInfo extends BaseEntity {

    private long bookId;
    private int allowComments;

    public BookInfo() {
    }

    public BookInfo(long bookId, int allowComments) {
        this.bookId = bookId;
        this.allowComments = allowComments;
    }

    public long getBookId() {
        return this.bookId;
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    public int getAllowComments() {
        return this.allowComments;
    }

    public void setAllowComments(int allowComments) {
        this.allowComments = allowComments;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
