package cn.chineseall.model.book;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

import cn.chineseall.model.BaseEntity;

/**
 * BookEditNew generated by hbm2java
 */
public class BookEditNew extends BaseEntity {

    /**  */
    private static final long serialVersionUID = 8692033406036555659L;
    
    private Integer id; // 流水号
    private long bookId; // 图书ID
    private Integer isRecommend; // 推荐标志 1：推荐 0：不推荐
    private Integer isNewBook; // 新书标志 1：新书 0：不是新书
    private Long needPoins; // 每本书需要的点数,同总库中默认为3
    private Long orgTreeId; // 机构编码（标记机构自己推荐的图书）
    private Date creationTime; // 创建时间

    public BookEditNew() {
    }

    public BookEditNew(long bookId) {
        this.bookId = bookId;
    }

    public BookEditNew(long bookId, Integer isRecommend, Integer isNewBook, Long needPoins, Long orgTreeId,
            Date creationTime) {
        this.bookId = bookId;
        this.isRecommend = isRecommend;
        this.isNewBook = isNewBook;
        this.needPoins = needPoins;
        this.orgTreeId = orgTreeId;
        this.creationTime = creationTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public long getBookId() {
        return this.bookId;
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    public Integer getIsRecommend() {
        return this.isRecommend;
    }

    public void setIsRecommend(Integer isRecommend) {
        this.isRecommend = isRecommend;
    }

    public Integer getIsNewBook() {
        return this.isNewBook;
    }

    public void setIsNewBook(Integer isNewBook) {
        this.isNewBook = isNewBook;
    }

    public Long getNeedPoins() {
        return this.needPoins;
    }

    public void setNeedPoins(Long needPoins) {
        this.needPoins = needPoins;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
