package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * SActionLog generated by hbm2java
 */
public class SActionLog extends BaseEntity {

    private Integer id;
    private long userId;
    private Long orgTreeId;
    private int type;
    private String data;
    private Date creationTime;

    public SActionLog() {
    }

    public SActionLog(long userId, int type) {
        this.userId = userId;
        this.type = type;
    }

    public SActionLog(long userId, Long orgTreeId, int type, String data, Date creationTime) {
        this.userId = userId;
        this.orgTreeId = orgTreeId;
        this.type = type;
        this.data = data;
        this.creationTime = creationTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
