package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * SUser generated by hbm2java
 */
public class SalesLog extends BaseEntity {


    private static final long serialVersionUID = 652011191209070157L;
    
    private Long id;
    private String salesNo;
    private int orgType;
    private Long orgTreeId;
    private Double salesPrice;
    private String salesPerson;
    private String salesBookList;
    private Date createTime;
    private Integer userId;
    
	@Override
	public String getKeyword() {
		return null;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getSalesNo() {
		return salesNo;
	}
	public void setSalesNo(String salesNo) {
		this.salesNo = salesNo;
	}
	public int getOrgType() {
		return orgType;
	}
	public void setOrgType(int orgType) {
		this.orgType = orgType;
	}
	public Long getOrgTreeId() {
		return orgTreeId;
	}
	public void setOrgTreeId(Long orgTreeId) {
		this.orgTreeId = orgTreeId;
	}
	public Double getSalesPrice() {
		return salesPrice;
	}
	public void setSalesPrice(Double salesPrice) {
		this.salesPrice = salesPrice;
	}
	public String getSalesPerson() {
		return salesPerson;
	}
	public void setSalesPerson(String salesPerson) {
		this.salesPerson = salesPerson;
	}
	public String getSalesBookList() {
		return salesBookList;
	}
	public void setSalesBookList(String salesBookList) {
		this.salesBookList = salesBookList;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
