package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * SDictionary generated by hbm2java
 */
public class SDictionary extends BaseEntity {

    private static final long serialVersionUID = -4277985666579155784L;

    private String code;
    private String name;
    private Integer state;

    public SDictionary() {
    }

    public SDictionary(String code) {
        this.code = code;
    }

    public SDictionary(String code, String name, Integer state) {
        this.code = code;
        this.name = name;
        this.state = state;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String getKeyword() {
        return this.getClass().getName() + "." + getCode();
    }

}
