package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * SPermit generated by hbm2java
 */
public class SPermit extends BaseEntity {

    private SPermitId id;
    private Long orgTreeId;
    private String name;

    public SPermit() {
    }

    public SPermit(SPermitId id) {
        this.id = id;
    }

    public SPermit(SPermitId id, Long orgTreeId, String name) {
        this.id = id;
        this.orgTreeId = orgTreeId;
        this.name = name;
    }

    public SPermitId getId() {
        return this.id;
    }

    public void setId(SPermitId id) {
        this.id = id;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
