package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * SPermitId generated by hbm2java
 */
public class SPermitId extends BaseEntity {

    private long id;
    private long userId;

    public SPermitId() {
    }

    public SPermitId(long id, long userId) {
        this.id = id;
        this.userId = userId;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SPermitId)) {
            return false;
        }
        SPermitId castOther = (SPermitId) other;

        return (this.getId() == castOther.getId()) && (this.getUserId() == castOther.getUserId());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getId();
        result = 37 * result + (int) this.getUserId();
        return result;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
