package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * SPoints generated by hbm2java
 */
public class SPoints extends BaseEntity {

    private Long id;
    private Integer pointCount;
    private Integer operCode;
    private String operName;
    private String operNote;

    public SPoints() {
    }

    public SPoints(Integer pointCount, Integer operCode, String operName, String operNote) {
        this.pointCount = pointCount;
        this.operCode = operCode;
        this.operName = operName;
        this.operNote = operNote;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPointCount() {
        return this.pointCount;
    }

    public void setPointCount(Integer pointCount) {
        this.pointCount = pointCount;
    }

    public Integer getOperCode() {
        return this.operCode;
    }

    public void setOperCode(Integer operCode) {
        this.operCode = operCode;
    }

    public String getOperName() {
        return this.operName;
    }

    public void setOperName(String operName) {
        this.operName = operName;
    }

    public String getOperNote() {
        return this.operNote;
    }

    public void setOperNote(String operNote) {
        this.operNote = operNote;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
