package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * SSearchWord generated by hbm2java
 */
public class SSearchWord extends BaseEntity {

    private Integer id;
    private int type;
    private String word;
    private Date creationTime;

    public SSearchWord() {
    }

    public SSearchWord(int type) {
        this.type = type;
    }

    public SSearchWord(int type, String word, Date creationTime) {
        this.type = type;
        this.word = word;
        this.creationTime = creationTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getWord() {
        return this.word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
