package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * SSlowMethodLog generated by hbm2java
 */
public class SSlowMethodLog extends BaseEntity {

    private Integer id;
    private String user;
    private int time;
    private String method;
    private Date creationTime;

    public SSlowMethodLog() {
    }

    public SSlowMethodLog(int time) {
        this.time = time;
    }

    public SSlowMethodLog(String user, int time, String method, Date creationTime) {
        this.user = user;
        this.time = time;
        this.method = method;
        this.creationTime = creationTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public int getTime() {
        return this.time;
    }

    public void setTime(int time) {
        this.time = time;
    }

    public String getMethod() {
        return this.method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
