package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * SUser generated by hbm2java
 */
public class SUser extends BaseEntity {


    private static final long serialVersionUID = 652011191209070157L;
    
    private Long id;
    private long userId;
    private int type;
    private Long orgTreeId;
    private Date creationTime;

    public SUser() {
    }

    public SUser(long userId, int type) {
        this.userId = userId;
        this.type = type;
    }

    public SUser(long userId, int type, Long orgTreeId, Date creationTime) {
        this.userId = userId;
        this.type = type;
        this.orgTreeId = orgTreeId;
        this.creationTime = creationTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public Long getOrgTreeId() {
        return this.orgTreeId;
    }

    public void setOrgTreeId(Long orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    public Date getCreationTime() {
        return this.creationTime;
    }

    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        return this.getClass().getName()+"_"+this.getUserId()+"_"+this.getOrgTreeId();
    }

}
