package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * SWebinfo generated by hbm2java
 */
public class SWebinfo extends BaseEntity {

    private int type;
    private long recordId;
    private String explain;
    private Date updateTime;

    public SWebinfo() {
    }

    public SWebinfo(int type, long recordId) {
        this.type = type;
        this.recordId = recordId;
    }

    public SWebinfo(int type, long recordId, String explain, Date updateTime) {
        this.type = type;
        this.recordId = recordId;
        this.explain = explain;
        this.updateTime = updateTime;
    }

    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public long getRecordId() {
        return this.recordId;
    }

    public void setRecordId(long recordId) {
        this.recordId = recordId;
    }

    public String getExplain() {
        return this.explain;
    }

    public void setExplain(String explain) {
        this.explain = explain;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
