package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * SWordunit generated by hbm2java
 */
public class SWordunit extends BaseEntity {
    // TODO keyword名字重复
    private Integer id;
    private String keyword;
    private Integer state;
    private Integer comment;
    private Integer signIn;

    public SWordunit() {
    }

    public SWordunit(String keyword, Integer state, Integer comment, Integer signIn) {
        this.keyword = keyword;
        this.state = state;
        this.comment = comment;
        this.signIn = signIn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String getKeyword() {
        return this.keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getComment() {
        return this.comment;
    }

    public void setComment(Integer comment) {
        this.comment = comment;
    }

    public Integer getSignIn() {
        return this.signIn;
    }

    public void setSignIn(Integer signIn) {
        this.signIn = signIn;
    }

}
