package cn.chineseall.model;

// Generated 2013-4-10 17:00:54 by Hibernate Tools 3.6.0

/**
 * TopNode generated by hbm2java
 */
public class TopNode extends BaseEntity {

    private Long id;
    private String name;
    private int state;
    private String domainName;

    public TopNode() {
    }

    public TopNode(String name, int state, String domainName) {
        this.name = name;
        this.state = state;
        this.domainName = domainName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getState() {
        return this.state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public String getDomainName() {
        return this.domainName;
    }

    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    /**
     * @see cn.chineseall.model.BaseEntity#getKeyword()
     */
    @Override
    public String getKeyword() {
        // TODO Auto-generated method stub
        return null;
    }

}
